### ISSUE TITLE
skeletons + extra enchants crash the game

### ISSUE THREAD

**Issue by Chuunkyz** [herb-mc/extra_enchants#11]
java.lang.NoSuchFieldError: sharpshooter
	at net.minecraft.class_1665.<init>(class_1665.java:88)
	at net.minecraft.class_1665.<init>(class_1665.java:94)
	at net.minecraft.class_1667.<init>(class_1667.java:44)
	at net.minecraft.class_2357$1.method_12844(class_2357.java:97)
	at net.minecraft.class_2965.method_10135(class_2965.java:20)
	at net.minecraft.class_2347.dispense(class_2347.java:15)
	at net.minecraft.class_2315.method_10012(class_2315.java:90)
	at net.minecraft.class_2315.method_9588(class_2315.java:113)
	at net.minecraft.class_4970$class_4971.method_26192(class_4970.java:918)
	at net.minecraft.class_3218.method_14189(class_3218.java:644)
	at net.minecraft.class_1949.method_8670(class_1949.java:81)
	at net.minecraft.class_3218.method_18765(class_3218.java:364)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:891)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
	at net.minecraft.class_1132.method_3748(class_1132.java:118)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by herb-mc** [comment]
Can you upload the full crash log for this? You can find it in .minecraft/crash-reports.
